/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SommelierRouteImport } from './routes/sommelier'
import { Route as ProducersRouteImport } from './routes/producers'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CharityRouteImport } from './routes/charity'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as IndexRouteImport } from './routes/index'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SommelierRoute = SommelierRouteImport.update({
  id: '/sommelier',
  path: '/sommelier',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducersRoute = ProducersRouteImport.update({
  id: '/producers',
  path: '/producers',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CharityRoute = CharityRouteImport.update({
  id: '/charity',
  path: '/charity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/charity': typeof CharityRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/investment': typeof InvestmentRoute
  '/marketplace': typeof MarketplaceRoute
  '/membership': typeof MembershipRoute
  '/producers': typeof ProducersRoute
  '/sommelier': typeof SommelierRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/charity': typeof CharityRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/investment': typeof InvestmentRoute
  '/marketplace': typeof MarketplaceRoute
  '/membership': typeof MembershipRoute
  '/producers': typeof ProducersRoute
  '/sommelier': typeof SommelierRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/charity': typeof CharityRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/investment': typeof InvestmentRoute
  '/marketplace': typeof MarketplaceRoute
  '/membership': typeof MembershipRoute
  '/producers': typeof ProducersRoute
  '/sommelier': typeof SommelierRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auctions'
    | '/charity'
    | '/dashboard'
    | '/events'
    | '/investment'
    | '/marketplace'
    | '/membership'
    | '/producers'
    | '/sommelier'
    | '/sponsors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auctions'
    | '/charity'
    | '/dashboard'
    | '/events'
    | '/investment'
    | '/marketplace'
    | '/membership'
    | '/producers'
    | '/sommelier'
    | '/sponsors'
  id:
    | '__root__'
    | '/'
    | '/auctions'
    | '/charity'
    | '/dashboard'
    | '/events'
    | '/investment'
    | '/marketplace'
    | '/membership'
    | '/producers'
    | '/sommelier'
    | '/sponsors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsRoute: typeof AuctionsRoute
  CharityRoute: typeof CharityRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  InvestmentRoute: typeof InvestmentRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MembershipRoute: typeof MembershipRoute
  ProducersRoute: typeof ProducersRoute
  SommelierRoute: typeof SommelierRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sommelier': {
      id: '/sommelier'
      path: '/sommelier'
      fullPath: '/sommelier'
      preLoaderRoute: typeof SommelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producers': {
      id: '/producers'
      path: '/producers'
      fullPath: '/producers'
      preLoaderRoute: typeof ProducersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charity': {
      id: '/charity'
      path: '/charity'
      fullPath: '/charity'
      preLoaderRoute: typeof CharityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsRoute: AuctionsRoute,
  CharityRoute: CharityRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  InvestmentRoute: InvestmentRoute,
  MarketplaceRoute: MarketplaceRoute,
  MembershipRoute: MembershipRoute,
  ProducersRoute: ProducersRoute,
  SommelierRoute: SommelierRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
