/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SommelierRouteImport } from './routes/sommelier'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProducersRouteImport } from './routes/producers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CharityRouteImport } from './routes/charity'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionsIndexRouteImport } from './routes/auctions.index'
import { Route as AuctionsDollywoodFoundation2026RouteImport } from './routes/auctions.dollywood-foundation-2026'
import { Route as AuctionsAuctionIdRouteImport } from './routes/auctions.$auctionId'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConciergeRouteImport } from './routes/_authenticated/concierge'
import { Route as AuthenticatedBidsRouteImport } from './routes/_authenticated/bids'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as AuthenticatedCheckoutReturnRouteImport } from './routes/_authenticated/checkout.return'
import { Route as AuthenticatedCheckoutMembershipRouteImport } from './routes/_authenticated/checkout.membership'
import { Route as AuthenticatedAdminConversionsRouteImport } from './routes/_authenticated/admin/conversions'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AuctionsAuctionIdLotsLotIdRouteImport } from './routes/auctions.$auctionId.lots.$lotId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicCronExpiryRemindersRouteImport } from './routes/api/public/cron/expiry-reminders'
import { Route as AuthenticatedAuctionsDollywoodFoundation2026LotsLotIdRouteImport } from './routes/_authenticated/auctions.dollywood-foundation-2026.lots.$lotId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SommelierRoute = SommelierRouteImport.update({
  id: '/sommelier',
  path: '/sommelier',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducersRoute = ProducersRouteImport.update({
  id: '/producers',
  path: '/producers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CharityRoute = CharityRouteImport.update({
  id: '/charity',
  path: '/charity',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuctionsRoute,
} as any)
const AuctionsDollywoodFoundation2026Route =
  AuctionsDollywoodFoundation2026RouteImport.update({
    id: '/dollywood-foundation-2026',
    path: '/dollywood-foundation-2026',
    getParentRoute: () => AuctionsRoute,
  } as any)
const AuctionsAuctionIdRoute = AuctionsAuctionIdRouteImport.update({
  id: '/$auctionId',
  path: '/$auctionId',
  getParentRoute: () => AuctionsRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConciergeRoute = AuthenticatedConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBidsRoute = AuthenticatedBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutReturnRoute =
  AuthenticatedCheckoutReturnRouteImport.update({
    id: '/checkout/return',
    path: '/checkout/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutMembershipRoute =
  AuthenticatedCheckoutMembershipRouteImport.update({
    id: '/checkout/membership',
    path: '/checkout/membership',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConversionsRoute =
  AuthenticatedAdminConversionsRouteImport.update({
    id: '/conversions',
    path: '/conversions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionIdLotsLotIdRoute =
  AuctionsAuctionIdLotsLotIdRouteImport.update({
    id: '/lots/$lotId',
    path: '/lots/$lotId',
    getParentRoute: () => AuctionsAuctionIdRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronExpiryRemindersRoute =
  ApiPublicCronExpiryRemindersRouteImport.update({
    id: '/api/public/cron/expiry-reminders',
    path: '/api/public/cron/expiry-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAuctionsDollywoodFoundation2026LotsLotIdRoute =
  AuthenticatedAuctionsDollywoodFoundation2026LotsLotIdRouteImport.update({
    id: '/auctions/dollywood-foundation-2026/lots/$lotId',
    path: '/auctions/dollywood-foundation-2026/lots/$lotId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auctions': typeof AuctionsRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/charity': typeof CharityRoute
  '/events': typeof EventsRoute
  '/investment': typeof InvestmentRoute
  '/marketplace': typeof MarketplaceRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/producers': typeof ProducersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sommelier': typeof SommelierRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/bids': typeof AuthenticatedBidsRoute
  '/concierge': typeof AuthenticatedConciergeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/admin/members': typeof AdminMembersRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRouteWithChildren
  '/auctions/dollywood-foundation-2026': typeof AuctionsDollywoodFoundation2026Route
  '/auctions/': typeof AuctionsIndexRoute
  '/admin/conversions': typeof AuthenticatedAdminConversionsRoute
  '/checkout/membership': typeof AuthenticatedCheckoutMembershipRoute
  '/checkout/return': typeof AuthenticatedCheckoutReturnRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/cron/expiry-reminders': typeof ApiPublicCronExpiryRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/auctions/$auctionId/lots/$lotId': typeof AuctionsAuctionIdLotsLotIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/auctions/dollywood-foundation-2026/lots/$lotId': typeof AuthenticatedAuctionsDollywoodFoundation2026LotsLotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/charity': typeof CharityRoute
  '/events': typeof EventsRoute
  '/investment': typeof InvestmentRoute
  '/marketplace': typeof MarketplaceRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/producers': typeof ProducersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sommelier': typeof SommelierRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/bids': typeof AuthenticatedBidsRoute
  '/concierge': typeof AuthenticatedConciergeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/admin/members': typeof AdminMembersRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRouteWithChildren
  '/auctions/dollywood-foundation-2026': typeof AuctionsDollywoodFoundation2026Route
  '/auctions': typeof AuctionsIndexRoute
  '/admin/conversions': typeof AuthenticatedAdminConversionsRoute
  '/checkout/membership': typeof AuthenticatedCheckoutMembershipRoute
  '/checkout/return': typeof AuthenticatedCheckoutReturnRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/cron/expiry-reminders': typeof ApiPublicCronExpiryRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/auctions/$auctionId/lots/$lotId': typeof AuctionsAuctionIdLotsLotIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/auctions/dollywood-foundation-2026/lots/$lotId': typeof AuthenticatedAuctionsDollywoodFoundation2026LotsLotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auctions': typeof AuctionsRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/charity': typeof CharityRoute
  '/events': typeof EventsRoute
  '/investment': typeof InvestmentRoute
  '/marketplace': typeof MarketplaceRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/producers': typeof ProducersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sommelier': typeof SommelierRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/bids': typeof AuthenticatedBidsRoute
  '/_authenticated/concierge': typeof AuthenticatedConciergeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/admin/members': typeof AdminMembersRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRouteWithChildren
  '/auctions/dollywood-foundation-2026': typeof AuctionsDollywoodFoundation2026Route
  '/auctions/': typeof AuctionsIndexRoute
  '/_authenticated/admin/conversions': typeof AuthenticatedAdminConversionsRoute
  '/_authenticated/checkout/membership': typeof AuthenticatedCheckoutMembershipRoute
  '/_authenticated/checkout/return': typeof AuthenticatedCheckoutReturnRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/cron/expiry-reminders': typeof ApiPublicCronExpiryRemindersRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/auctions/$auctionId/lots/$lotId': typeof AuctionsAuctionIdLotsLotIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/auctions/dollywood-foundation-2026/lots/$lotId': typeof AuthenticatedAuctionsDollywoodFoundation2026LotsLotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auctions'
    | '/auth'
    | '/calendar'
    | '/charity'
    | '/events'
    | '/investment'
    | '/marketplace'
    | '/membership'
    | '/privacy'
    | '/producers'
    | '/reset-password'
    | '/sommelier'
    | '/sponsors'
    | '/terms'
    | '/admin'
    | '/bids'
    | '/concierge'
    | '/dashboard'
    | '/watchlist'
    | '/admin/members'
    | '/auctions/$auctionId'
    | '/auctions/dollywood-foundation-2026'
    | '/auctions/'
    | '/admin/conversions'
    | '/checkout/membership'
    | '/checkout/return'
    | '/lovable/email/events'
    | '/api/public/cron/expiry-reminders'
    | '/api/public/payments/webhook'
    | '/auctions/$auctionId/lots/$lotId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/auctions/dollywood-foundation-2026/lots/$lotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/calendar'
    | '/charity'
    | '/events'
    | '/investment'
    | '/marketplace'
    | '/membership'
    | '/privacy'
    | '/producers'
    | '/reset-password'
    | '/sommelier'
    | '/sponsors'
    | '/terms'
    | '/admin'
    | '/bids'
    | '/concierge'
    | '/dashboard'
    | '/watchlist'
    | '/admin/members'
    | '/auctions/$auctionId'
    | '/auctions/dollywood-foundation-2026'
    | '/auctions'
    | '/admin/conversions'
    | '/checkout/membership'
    | '/checkout/return'
    | '/lovable/email/events'
    | '/api/public/cron/expiry-reminders'
    | '/api/public/payments/webhook'
    | '/auctions/$auctionId/lots/$lotId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/auctions/dollywood-foundation-2026/lots/$lotId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auctions'
    | '/auth'
    | '/calendar'
    | '/charity'
    | '/events'
    | '/investment'
    | '/marketplace'
    | '/membership'
    | '/privacy'
    | '/producers'
    | '/reset-password'
    | '/sommelier'
    | '/sponsors'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/bids'
    | '/_authenticated/concierge'
    | '/_authenticated/dashboard'
    | '/_authenticated/watchlist'
    | '/admin/members'
    | '/auctions/$auctionId'
    | '/auctions/dollywood-foundation-2026'
    | '/auctions/'
    | '/_authenticated/admin/conversions'
    | '/_authenticated/checkout/membership'
    | '/_authenticated/checkout/return'
    | '/lovable/email/events'
    | '/api/public/cron/expiry-reminders'
    | '/api/public/payments/webhook'
    | '/auctions/$auctionId/lots/$lotId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/auctions/dollywood-foundation-2026/lots/$lotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuctionsRoute: typeof AuctionsRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  CharityRoute: typeof CharityRoute
  EventsRoute: typeof EventsRoute
  InvestmentRoute: typeof InvestmentRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MembershipRoute: typeof MembershipRoute
  PrivacyRoute: typeof PrivacyRoute
  ProducersRoute: typeof ProducersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SommelierRoute: typeof SommelierRoute
  SponsorsRoute: typeof SponsorsRoute
  TermsRoute: typeof TermsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  ApiPublicCronExpiryRemindersRoute: typeof ApiPublicCronExpiryRemindersRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sommelier': {
      id: '/sommelier'
      path: '/sommelier'
      fullPath: '/sommelier'
      preLoaderRoute: typeof SommelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producers': {
      id: '/producers'
      path: '/producers'
      fullPath: '/producers'
      preLoaderRoute: typeof ProducersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charity': {
      id: '/charity'
      path: '/charity'
      fullPath: '/charity'
      preLoaderRoute: typeof CharityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/auctions/dollywood-foundation-2026': {
      id: '/auctions/dollywood-foundation-2026'
      path: '/dollywood-foundation-2026'
      fullPath: '/auctions/dollywood-foundation-2026'
      preLoaderRoute: typeof AuctionsDollywoodFoundation2026RouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/auctions/$auctionId': {
      id: '/auctions/$auctionId'
      path: '/$auctionId'
      fullPath: '/auctions/$auctionId'
      preLoaderRoute: typeof AuctionsAuctionIdRouteImport
      parentRoute: typeof AuctionsRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concierge': {
      id: '/_authenticated/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof AuthenticatedConciergeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bids': {
      id: '/_authenticated/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof AuthenticatedBidsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout/return': {
      id: '/_authenticated/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof AuthenticatedCheckoutReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/membership': {
      id: '/_authenticated/checkout/membership'
      path: '/checkout/membership'
      fullPath: '/checkout/membership'
      preLoaderRoute: typeof AuthenticatedCheckoutMembershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/conversions': {
      id: '/_authenticated/admin/conversions'
      path: '/conversions'
      fullPath: '/admin/conversions'
      preLoaderRoute: typeof AuthenticatedAdminConversionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionId/lots/$lotId': {
      id: '/auctions/$auctionId/lots/$lotId'
      path: '/lots/$lotId'
      fullPath: '/auctions/$auctionId/lots/$lotId'
      preLoaderRoute: typeof AuctionsAuctionIdLotsLotIdRouteImport
      parentRoute: typeof AuctionsAuctionIdRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/expiry-reminders': {
      id: '/api/public/cron/expiry-reminders'
      path: '/api/public/cron/expiry-reminders'
      fullPath: '/api/public/cron/expiry-reminders'
      preLoaderRoute: typeof ApiPublicCronExpiryRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auctions/dollywood-foundation-2026/lots/$lotId': {
      id: '/_authenticated/auctions/dollywood-foundation-2026/lots/$lotId'
      path: '/auctions/dollywood-foundation-2026/lots/$lotId'
      fullPath: '/auctions/dollywood-foundation-2026/lots/$lotId'
      preLoaderRoute: typeof AuthenticatedAuctionsDollywoodFoundation2026LotsLotIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminConversionsRoute: typeof AuthenticatedAdminConversionsRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminConversionsRoute: AuthenticatedAdminConversionsRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBidsRoute: typeof AuthenticatedBidsRoute
  AuthenticatedConciergeRoute: typeof AuthenticatedConciergeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedCheckoutMembershipRoute: typeof AuthenticatedCheckoutMembershipRoute
  AuthenticatedCheckoutReturnRoute: typeof AuthenticatedCheckoutReturnRoute
  AuthenticatedAuctionsDollywoodFoundation2026LotsLotIdRoute: typeof AuthenticatedAuctionsDollywoodFoundation2026LotsLotIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBidsRoute: AuthenticatedBidsRoute,
  AuthenticatedConciergeRoute: AuthenticatedConciergeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedCheckoutMembershipRoute: AuthenticatedCheckoutMembershipRoute,
  AuthenticatedCheckoutReturnRoute: AuthenticatedCheckoutReturnRoute,
  AuthenticatedAuctionsDollywoodFoundation2026LotsLotIdRoute:
    AuthenticatedAuctionsDollywoodFoundation2026LotsLotIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuctionsAuctionIdRouteChildren {
  AuctionsAuctionIdLotsLotIdRoute: typeof AuctionsAuctionIdLotsLotIdRoute
}

const AuctionsAuctionIdRouteChildren: AuctionsAuctionIdRouteChildren = {
  AuctionsAuctionIdLotsLotIdRoute: AuctionsAuctionIdLotsLotIdRoute,
}

const AuctionsAuctionIdRouteWithChildren =
  AuctionsAuctionIdRoute._addFileChildren(AuctionsAuctionIdRouteChildren)

interface AuctionsRouteChildren {
  AuctionsAuctionIdRoute: typeof AuctionsAuctionIdRouteWithChildren
  AuctionsDollywoodFoundation2026Route: typeof AuctionsDollywoodFoundation2026Route
  AuctionsIndexRoute: typeof AuctionsIndexRoute
}

const AuctionsRouteChildren: AuctionsRouteChildren = {
  AuctionsAuctionIdRoute: AuctionsAuctionIdRouteWithChildren,
  AuctionsDollywoodFoundation2026Route: AuctionsDollywoodFoundation2026Route,
  AuctionsIndexRoute: AuctionsIndexRoute,
}

const AuctionsRouteWithChildren = AuctionsRoute._addFileChildren(
  AuctionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuctionsRoute: AuctionsRouteWithChildren,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  CharityRoute: CharityRoute,
  EventsRoute: EventsRoute,
  InvestmentRoute: InvestmentRoute,
  MarketplaceRoute: MarketplaceRoute,
  MembershipRoute: MembershipRoute,
  PrivacyRoute: PrivacyRoute,
  ProducersRoute: ProducersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SommelierRoute: SommelierRoute,
  SponsorsRoute: SponsorsRoute,
  TermsRoute: TermsRoute,
  AdminMembersRoute: AdminMembersRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  ApiPublicCronExpiryRemindersRoute: ApiPublicCronExpiryRemindersRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
